.\" Copyright (c) 2021 Omar Polo <op@omarpolo.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: December 02 2021$
.Dt NINEPSCRIPT 8
.Os
.Sh NAME
.Nm ninepscript
.Nd scripting language for the kamid regress suite
.Sh SYNOPSIS
.Nm
.Op Fl nv
.Op Fl x Ar pattern
.Ar
.Sh DESCRIPTION
.Nm
is an interpreter for a custom DSL
.Pq domain sppecific language
used to write the regression suite of
.Xr kamid 8 .
The test themselves are written in
.Xr ninepscript 5 .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl n
don't run the test, check only the syntax of the provided
.Ar files .
.It Fl v
verbose logging, print more information during the tests execution.
.It Fl x Ar pattern
Run only the tests that match the given
.Ar pattern .
.El
.Pp
.Nm
first loads all the given
.Ar files
then proceeds to execute each defined test.
.Pp
See
.Xr ninepscript 5
for the description of the ninepscript language.
