#!/bin/sh
#
# Copyright (c) 2022 Omar Polo <op@omarpolo.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# subst -- filter that replaces key=values pairs
#
# usage: subst key1=val1 [... keyn=valn] [files...]
#
# Use `--' before the first file if it may contain an = in its name.
# If no files are given, read and substitute from standard input.

args=''

for arg; do
	if [ "$arg" = '--' ]; then
		break
	fi

	key="$(printf '%s\n' $arg | cut -s -d '=' -f1)"
	if [ -z "$key" ]; then
		break
	fi
	val="$(printf '%s\n' $arg | cut -d '=' -f 2-)"
	shift

	args="$args -e s/$key/$val/g "
done

exec sed $args "$@"
